title: Home Lab & Automation
description: Documentation of my home lab and home automation 
theme: just-the-docs

url: https://homelab.themakermedic.com

aux_links:
  The Maker Medic: https://themakermedic.com

color_scheme: lab

plugins:
 - jemoji