title: HomeLab Docs
description: A reference document for my HomeLab Build
theme: just-the-docs

url: https://homelabdocs.themakermedic.com/

aux_links:
  The Maker Medic: https://themakermedic.com

color_scheme: dark

plugins:
 - jemoji

callouts:
  warning:
    title: warning
    color: red
  note:
    title: note
    color: yellow
  info:
    title: info
    color: grey-dk
  tip:
    title: tip
    color: green 
  credits:
    title: credit
    color: purple   

defaults:
  - scope:
      path: "docs" # an empty string here means all files in the project
      type: "pages"
    values:
      layout: "default"    